package parser

//go:generate pigeon -optimize-parser -optimize-grammar -alternate-entrypoints DefaultDocumentFragmentElement,DocumentFragmentElementWithinParagraph,DocumentFragmentElementWithinVerbatimBlock,DocumentFragmentElementWithinNormalBlock,NormalGroup,HeaderGroup,AttributesGroup,MacrosGroup,QuotesGroup,NoneGroup,ReplacementsGroup,SpecialCharactersGroup,VerbatimGroup,FileLocation,IncludedFileLine,BlockAttributes,InlineAttributes,LineRanges,TagRanges -o parser.go parser.peg
